export default [
  /* {
     id: 1,
    name: 'Continuous demixing transition of binary liquids: finite-size scaling from the analysis of sub-systems',
    img: 'img/theme/bootstrap.jpg',
    author: 'Caleb Hoff, Jashandeep Singh Kaleka, Greg, Mehmet',
    date: '2020',
    journal: 'UTD 2021 journal',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Coming Soon',
    rating: 60
  },
  {
    id: 2,
    name: 'Precise phase control of large-scale inorganic perovskites via vapor-phase anion-exchange strategy',
    img: 'img/theme/angular.jpg',
    author: 'Caleb Hoff',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 100
  },
  {
    id: 3,
    name: 'Investigating institutional influence on graduate program admissions by modelling physics GRE cut-off scores',
    img: 'img/theme/sketch.jpg',
    author: 'Mehmet Gunal',
    date: '2021',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Email Author',
    rating: 72
  },
  {
    id: 4,
    name: 'John von Neumann\'s 1950s Change to Philosopher of Computation',
    img: 'img/theme/react.jpg',
    author: 'Spencer Balog',
    date: '2020',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Email Author',
    rating: 90
  },
  {
    id: 5,
    name: 'An information theoretic network approach to socioeconomic correlations',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '1986',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 100
  },
  {
    id: 6,
    name: 'A posteriori corrections to the Iterative Qubit Coupled Cluster method to minimize the use of quantum resources in large-scale calculations',
    img: 'img/theme/bootstrap.jpg',
    author: 'Greg Kitchen',
    date: '2017',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Email Author',
    rating: 60
  },
  {
    id: 7,
    name: 'Towards Universal Sparse Gaussian Process Potentials: Application to Lithium Diffusivity in Superionic Conducting Solid Electrolytes',
    img: 'img/theme/angular.jpg',
    author: 'Mehmet Gunal',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 100
  },
  {
    id: 8,
    name: 'Universal coherent structures of elastic turbulence in straight channel with viscoelastic fluid flow',
    img: 'img/theme/sketch.jpg',
    author: 'Daksh Kapur',
    date: '2018',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Coming Soon',
    rating: 72
  },
  {
    id: 9,
    name: 'Novel Technosignatures',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '2011',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 100
  },
  {
    id: 10,
    name: 'Implications of Gravitational-wave Production from Dark Photon Resonance to NANOGrav Observations and Effective number of Relativistic Species',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 80
  },
  {
    id: 11,
    name: 'Implications of Gravitational-wave Production from Dark Photon Resonance to NANOGrav Observations and Effective number of Relativistic Species',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 80
  },
  {
    id: 12,
    name: 'Implications of Gravitational-wave Production from Dark Photon Resonance to NANOGrav Observations and Effective number of Relativistic Species',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 80
  },
  {
    id: 13,
    name: 'Implications of Gravitational-wave Production from Dark Photon Resonance to NANOGrav Observations and Effective number of Relativistic Species',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 80
  },
  {
    id: 14,
    name: 'Implications of Gravitational-wave Production from Dark Photon Resonance to NANOGrav Observations and Effective number of Relativistic Species',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 80
  },
  {
    id: 15,
    name: 'Implications of Gravitational-wave Production from Dark Photon Resonance to NANOGrav Observations and Effective number of Relativistic Species',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 80
  },
  {
    id: 16,
    name: 'Implications of Gravitational-wave Production from Dark Photon Resonance to NANOGrav Observations and Effective number of Relativistic Species',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 80
  },
  {
    id: 17,
    name: 'Implications of Gravitational-wave Production from Dark Photon Resonance to NANOGrav Observations and Effective number of Relativistic Species',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 80
  },
  {
    id: 18,
    name: 'Implications of Gravitational-wave Production from Dark Photon Resonance to NANOGrav Observations and Effective number of Relativistic Species',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 80
  },
  {
    id: 19,
    name: 'Implications of Gravitational-wave Production from Dark Photon Resonance to NANOGrav Observations and Effective number of Relativistic Species',
    img: 'img/theme/vue.jpg',
    author: 'Caleb Hoff',
    date: '2019',
    abstract: 'Anion exchange offers great flexibility and high precision in phase control, compositional engineering and optoelectronic property tuning. Different from previous successful anion exchange process in liquid solution, herein, we develop a vapor-phase anion-exchange strategy to realize the precise phase and bandgap control of large-scale inorganic perovskites by using gas injection cycle, produing some perovskites such as CsPbCl3 which has never been reported in thin film morphology. Ab-initio calculations also provide the insightful mechanism to understand the impact of anion exchange on tuning the electronic properties and optimizing the structural stability. Furthermore, because of precise control of specific atomic concentrations, intriguing tunable photoluminsecence is observed and photodetectors with tunable photoresponse edge from green to ultraviolet light can be realized accurately with an ultrahigh spectral resolution of 1 nm. Therefore, we offer a new, universal vapor-phase anion exchange method for inorganic perovskite with fine-tunable optoelectronic properties.',
    status: 'Available',
    rating: 80
  },
  */
    {
        "author": "Ahmed Osman, Wojciech Samek",
        "day": 1,
        "id": "1802.00209v1",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1802.00209v1', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1802.00209v1', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 2,
        "abstract": "We propose an architecture for VQA which utilizes recurrent layers to\ngenerate visual and textual attention. The memory characteristic of the\nproposed recurrent attention units offers a rich joint embedding of visual and\ntextual features and enables the model to reason relations between several\nparts of the image and question. Our single model outperforms the first place\nwinner on the VQA 1.0 dataset, performs within margin to the current\nstate-of-the-art ensemble model. We also experiment with replacing attention\nmechanisms in other state-of-the-art models with our implementation and show\nincreased accuracy. In both cases, our recurrent attention mechanism improves\nperformance in tasks requiring sequential or relational reasoning on the VQA\ndataset.",
        "tag": "[{'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Dual Recurrent Attention Units for Visual Question Answering",
        "year": 2018,
        "journal": "Computer Vision and Image Understanding"
    },
    {
        "author": "Ji Young Lee, Franck Dernoncourt",
        "day": 12,
        "id": "1603.03827v1",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1603.03827v1', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1603.03827v1', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 3,
        "abstract": "Recent approaches based on artificial neural networks (ANNs) have shown\npromising results for short-text classification. However, many short texts\noccur in sequences (e.g., sentences in a document or utterances in a dialog),\nand most existing ANN-based systems do not leverage the preceding short texts\nwhen classifying a subsequent one. In this work, we present a model based on\nrecurrent neural networks and convolutional neural networks that incorporates\nthe preceding short texts. Our model achieves state-of-the-art results on three\ndifferent datasets for dialog act prediction.",
        "tag": "[{'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Sequential Short-Text Classification with Recurrent and Convolutional\n  Neural Networks",
        "year": 2016,
        "journal": "Proceedings of the AAAI Conference on Artificial Intelligence"
    },
    {
        "author": "Kartik Talamadupula, Bowen Zhou",
        "day": 2,
        "id": "1606.00776v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1606.00776v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1606.00776v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 6,
        "abstract": "We introduce the multiresolution recurrent neural network, which extends the\nsequence-to-sequence framework to model natural language generation as two\nparallel discrete stochastic processes: a sequence of high-level coarse tokens,\nand a sequence of natural language tokens. There are many ways to estimate or\nlearn the high-level coarse tokens, but we argue that a simple extraction\nprocedure is sufficient to capture a wealth of high-level discourse semantics.\nSuch procedure allows training the multiresolution recurrent neural network by\nmaximizing the exact joint log-likelihood over both sequences. In contrast to\nthe standard log- likelihood objective w.r.t. natural language tokens (word\nperplexity), optimizing the joint log-likelihood biases the model towards\nmodeling high-level abstractions. We apply the proposed model to the task of\ndialogue response generation in two challenging domains: the Ubuntu technical\nsupport domain, and Twitter conversations. On Ubuntu, the model outperforms\ncompeting approaches by a substantial margin, achieving state-of-the-art\nresults according to both automatic evaluation metrics and a human evaluation\nstudy. On Twitter, the model appears to generate more relevant and on-topic\nresponses according to automatic evaluation metrics. Finally, our experiments\ndemonstrate that the proposed model is more adept at overcoming the sparsity of\nnatural language and is better able to capture long-term structure.",
        "tag": "[{'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'I.5.1; I.2.7', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Multiresolution Recurrent Neural Networks: An Application to Dialogue\n  Response Generation",
        "year": 2011,
        "journal": "Proceedings of the 2011 Conference on Empirical Methods"
    },
    {
        "author": "Sebastian Ruder, Joachim Bingel, Isabelle Augenstein",
        "day": 23,
        "id": "1705.08142v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1705.08142v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1705.08142v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 5,
        "abstract": "Multi-task learning is motivated by the observation that humans bring to bear\nwhat they know about related problems when solving new ones. Similarly, deep\nneural networks can profit from related tasks by sharing parameters with other\nnetworks. However, humans do not consciously decide to transfer knowledge\nbetween tasks. In Natural Language Processing (NLP), it is hard to predict if\nsharing will lead to improvements, particularly if tasks are only loosely\nrelated. To overcome this, we introduce Sluice Networks, a general framework\nfor multi-task learning where trainable parameters control the amount of\nsharing. Our framework generalizes previous proposals in enabling sharing of\nall combinations of subspaces, layers, and skip connections. We perform\nexperiments on three task pairs, and across seven different domains, using data\nfrom OntoNotes 5.0, and achieve up to 15% average error reductions over common\napproaches to multi-task learning. We show that a) label entropy is predictive\nof gains in sluice networks, confirming findings for hard parameter sharing and\nb) while sluice networks easily fit noise, they are robust across domains in\npractice.",
        "tag": "[{'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Learning what to share between loosely related tasks",
        "year": 2017,
        "journal": "IEEE Transactions on Geoscience and Remote Sensing"
    },
    {
        "author": "Iulian V. Serban, Chinnadhurai Sankar, Taesup Kim, Michael Pieper",
        "day": 7,
        "id": "1709.02349v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1709.02349v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1709.02349v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 9,
        "abstract": "We present MILABOT: a deep reinforcement learning chatbot developed by the\nMontreal Institute for Learning Algorithms (MILA) for the Amazon Alexa Prize\ncompetition. MILABOT is capable of conversing with humans on popular small talk\ntopics through both speech and text. The system consists of an ensemble of\nnatural language generation and retrieval models, including template-based\nmodels, bag-of-words models, sequence-to-sequence neural network and latent\nvariable neural network models. By applying reinforcement learning to\ncrowdsourced data and real-world user interactions, the system has been trained\nto select an appropriate response from the models in its ensemble. The system\nhas been evaluated through A/B testing with real-world users, where it\nperformed significantly better than many competing systems. Due to its machine\nlearning architecture, the system is likely to improve with additional data.",
        "tag": "[{'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'I.5.1; I.2.7', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "A Deep Reinforcement Learning Chatbot",
        "year": 2017,
        "journal": "2017 International Joint Conference on Neural Networks"
    },
    {
        "author": "Kelvin Guu, Tatsunori B. Hashimoto, Yonatan Oren, Percy Liang",
        "day": 26,
        "id": "1709.08878v1",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1709.08878v1', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1709.08878v1', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 9,
        "abstract": "We propose a new generative model of sentences that first samples a prototype\nsentence from the training corpus and then edits it into a new sentence.\nCompared to traditional models that generate from scratch either left-to-right\nor by first sampling a latent sentence vector, our prototype-then-edit model\nimproves perplexity on language modeling and generates higher quality outputs\naccording to human evaluation. Furthermore, the model gives rise to a latent\nedit vector that captures interpretable semantics such as sentence similarity\nand sentence-level analogies.",
        "tag": "[{'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Generating Sentences by Editing Prototypes",
        "year": 2017,
        "journal": "Transactions of the Association for Computational Linguistics"
    },
    {
        "author": "Iulian V. Serban, Chinnadhurai Sankar",
        "day": 20,
        "id": "1801.06700v1",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1801.06700v1', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1801.06700v1', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 1,
        "abstract": "We present MILABOT: a deep reinforcement learning chatbot developed by the\nMontreal Institute for Learning Algorithms (MILA) for the Amazon Alexa Prize\ncompetition. MILABOT is capable of conversing with humans on popular small talk\ntopics through both speech and text. The system consists of an ensemble of\nnatural language generation and retrieval models, including neural network and\ntemplate-based models. By applying reinforcement learning to crowdsourced data\nand real-world user interactions, the system has been trained to select an\nappropriate response from the models in its ensemble. The system has been\nevaluated through A/B testing with real-world users, where it performed\nsignificantly better than other systems. The results highlight the potential of\ncoupling ensemble systems with deep reinforcement learning as a fruitful path\nfor developing real-world, open-domain conversational agents.",
        "tag": "[{'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'I.5.1; I.2.7', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "A Deep Reinforcement Learning Chatbot (Short Version)",
        "year": 2018,
        "journal": "arXiv preprint arXiv:1709.02349"
    },
    {
        "author": "Darko Brodic, Alessia Amelio, Zoran N. Milivojevic, Milena Jevtic",
        "day": 21,
        "id": "1609.06492v1",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1609.06492v1', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1609.06492v1', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 9,
        "abstract": "The paper introduces a new method for discrimination of documents given in\ndifferent scripts. The document is mapped into a uniformly coded text of\nnumerical values. It is derived from the position of the letters in the text\nline, based on their typographical characteristics. Each code is considered as\na gray level. Accordingly, the coded text determines a 1-D image, on which\ntexture analysis by run-length statistics and local binary pattern is\nperformed. It defines feature vectors representing the script content of the\ndocument. A modified clustering approach employed on document feature vector\ngroups documents written in the same script. Experimentation performed on two\ncustom oriented databases of historical documents in old Cyrillic, angular and\nround Glagolitic as well as Antiqua and Fraktur scripts demonstrates the\nsuperiority of the proposed method with respect to well-known methods in the\nstate-of-the-art.",
        "tag": "[{'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': '97R40, 62H35, 68U15, 68T50,', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Document Image Coding and Clustering for Script Discrimination",
        "year": 2016,
        "journal": "Neural Computing and Applications"
    },
    {
        "author": "Mateusz Malinowski, Mario Fritz",
        "day": 4,
        "id": "1610.01076v1",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1610.01076v1', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1610.01076v1', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 10,
        "abstract": "Together with the development of more accurate methods in Computer Vision and\nNatural Language Understanding, holistic architectures that answer on questions\nabout the content of real-world images have emerged. In this tutorial, we build\na neural-based approach to answer questions about images. We base our tutorial\non two datasets: (mostly on) DAQUAR, and (a bit on) VQA. With small tweaks the\nmodels that we present here can achieve a competitive performance on both\ndatasets, in fact, they are among the best methods that use a combination of\nLSTM with a global, full frame CNN representation of an image. We hope that\nafter reading this tutorial, the reader will be able to use Deep Learning\nframeworks, such as Keras and introduced Kraino, to build various architectures\nthat will lead to a further performance improvement on this challenging task.",
        "tag": "[{'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Tutorial on Answering Questions about Images with Deep Learning",
        "year": 2016,
        "journal" : "Proceedings of the 39th International ACM SIGIR conference"
    },
    {
        "author": "Tony Beltramelli",
        "day": 22,
        "id": "1705.07962v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1705.07962v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1705.07962v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 5,
        "abstract": "Transforming a graphical user interface screenshot created by a designer into\ncomputer code is a typical task conducted by a developer in order to build\ncustomized software, websites, and mobile applications. In this paper, we show\nthat deep learning methods can be leveraged to train a model end-to-end to\nautomatically generate code from a single input image with over 77% of accuracy\nfor three different platforms (i.e. iOS, Android and web-based technologies).",
        "tag": "[{'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': '68T45', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'I.2.1; I.2.10; I.2.2; I.2.6', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "pix2code: Generating Code from a Graphical User Interface Screenshot",
        "year": 2017,
        "journal" : "Proceedings of the ACM SIGCHI Symposium"
    },
    {
        "author": "Fred Richardson, Douglas Reynolds, Najim Dehak",
        "day": 3,
        "id": "1504.00923v1",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1504.00923v1', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1504.00923v1', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 4,
        "abstract": "Learned feature representations and sub-phoneme posteriors from Deep Neural\nNetworks (DNNs) have been used separately to produce significant performance\ngains for speaker and language recognition tasks. In this work we show how\nthese gains are possible using a single DNN for both speaker and language\nrecognition. The unified DNN approach is shown to yield substantial performance\nimprovements on the the 2013 Domain Adaptation Challenge speaker recognition\ntask (55% reduction in EER for the out-of-domain condition) and on the NIST\n2011 Language Recognition Evaluation (48% reduction in EER for the 30s test\ncondition).",
        "tag": "[{'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "A Unified Deep Neural Network for Speaker and Language Recognition",
        "year": 2015,
        "journal": "IEEE/ACM Transactions on Audio, Speech, and Language Processing"
    },
    {
        "author": "Hieu Pham, Melody Y. Guan, Barret Zoph, Quoc V. Le, Jeff Dean",
        "day": 9,
        "id": "1802.03268v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1802.03268v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1802.03268v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 2,
        "abstract": "We propose Efficient Neural Architecture Search (ENAS), a fast and\ninexpensive approach for automatic model design. In ENAS, a controller learns\nto discover neural network architectures by searching for an optimal subgraph\nwithin a large computational graph. The controller is trained with policy\ngradient to select a subgraph that maximizes the expected reward on the\nvalidation set. Meanwhile the model corresponding to the selected subgraph is\ntrained to minimize a canonical cross entropy loss. Thanks to parameter sharing\nbetween child models, ENAS is fast: it delivers strong empirical performances\nusing much fewer GPU-hours than all existing automatic model design approaches,\nand notably, 1000x less expensive than standard Neural Architecture Search. On\nthe Penn Treebank dataset, ENAS discovers a novel architecture that achieves a\ntest perplexity of 55.8, establishing a new state-of-the-art among all methods\nwithout post-training processing. On the CIFAR-10 dataset, ENAS designs novel\narchitectures that achieve a test error of 2.89%, which is on par with NASNet\n(Zoph et al., 2018), whose test error is 2.65%.",
        "tag": "[{'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CL', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Efficient Neural Architecture Search via Parameter Sharing",
        "year": 2018,
        "journal": "International Conference on Machine Learning"
    },
    {
        "author": "Brenden M. Lake, Tomer D. Ullman, Joshua B. Tenenbaum, Samuel J. Gershman",
        "day": 1,
        "id": "1604.00289v3",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1604.00289v3', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1604.00289v3', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 4,
        "abstract": "Recent progress in artificial intelligence (AI) has renewed interest in\nbuilding systems that learn and think like people. Many advances have come from\nusing deep neural networks trained end-to-end in tasks such as object\nrecognition, video games, and board games, achieving performance that equals or\neven beats humans in some respects. Despite their biological inspiration and\nperformance achievements, these systems differ from human intelligence in\ncrucial ways. We review progress in cognitive science suggesting that truly\nhuman-like learning and thinking machines will have to reach beyond current\nengineering trends in both what they learn, and how they learn it.\nSpecifically, we argue that these machines should (a) build causal models of\nthe world that support explanation and understanding, rather than merely\nsolving pattern recognition problems; (b) ground learning in intuitive theories\nof physics and psychology, to support and enrich the knowledge that is learned;\nand (c) harness compositionality and learning-to-learn to rapidly acquire and\ngeneralize knowledge to new tasks and situations. We suggest concrete\nchallenges and promising routes towards these goals that can combine the\nstrengths of recent neural network advances with more structured cognitive\nmodels.",
        "tag": "[{'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Building Machines That Learn and Think Like People",
        "year": 2016,
        "journal": "Behavioral and brain sciences 40"
    },
    {
        "author": "Hao Wang, Dit-Yan Yeung",
        "day": 6,
        "id": "1604.01662v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1604.01662v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1604.01662v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 4,
        "abstract": "While perception tasks such as visual object recognition and text\nunderstanding play an important role in human intelligence, the subsequent\ntasks that involve inference, reasoning and planning require an even higher\nlevel of intelligence. The past few years have seen major advances in many\nperception tasks using deep learning models. For higher-level inference,\nhowever, probabilistic graphical models with their Bayesian nature are still\nmore powerful and flexible. To achieve integrated intelligence that involves\nboth perception and inference, it is naturally desirable to tightly integrate\ndeep learning and Bayesian models within a principled probabilistic framework,\nwhich we call Bayesian deep learning. In this unified framework, the perception\nof text or images using deep learning can boost the performance of higher-level\ninference and in return, the feedback from the inference process is able to\nenhance the perception of text or images. This survey provides a general\nintroduction to Bayesian deep learning and reviews its recent applications on\nrecommender systems, topic models, and control. In this survey, we also discuss\nthe relationship and differences between Bayesian deep learning and other\nrelated topics like Bayesian treatment of neural networks.",
        "tag": "[{'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Towards Bayesian Deep Learning: A Survey",
        "year": 2016,
        "journal": "IEEE Transactions on Knowledge and Data Engineering"
    },
    {
        "author": "Tejas D. Kulkarni, Karthik R. Narasimhan, Ardavan Saeedi, Joshua B. Tenenbaum",
        "day": 20,
        "id": "1604.06057v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1604.06057v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1604.06057v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 4,
        "abstract": "Learning goal-directed behavior in environments with sparse feedback is a\nmajor challenge for reinforcement learning algorithms. The primary difficulty\narises due to insufficient exploration, resulting in an agent being unable to\nlearn robust value functions. Intrinsically motivated agents can explore new\nbehavior for its own sake rather than to directly solve problems. Such\nintrinsic behaviors could eventually help the agent solve tasks posed by the\nenvironment. We present hierarchical-DQN (h-DQN), a framework to integrate\nhierarchical value functions, operating at different temporal scales, with\nintrinsically motivated deep reinforcement learning. A top-level value function\nlearns a policy over intrinsic goals, and a lower-level function learns a\npolicy over atomic actions to satisfy the given goals. h-DQN allows for\nflexible goal specifications, such as functions over entities and relations.\nThis provides an efficient space for exploration in complicated environments.\nWe demonstrate the strength of our approach on two problems with very sparse,\ndelayed feedback: (1) a complex discrete stochastic decision process, and (2)\nthe classic ATARI game `Montezuma's Revenge'.",
        "tag": "[{'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Hierarchical Deep Reinforcement Learning: Integrating Temporal\n  Abstraction and Intrinsic Motivation",
        "year": 2016,
        "journal": "Proceedings of the 17th International Conference on Autonomous Agents"
    },
    {
        "author": "Deepak Pathak, Ross Girshick, Piotr Doll, Trevor Darrell, Bharath Hariharan",
        "day": 19,
        "id": "1612.06370v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1612.06370v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1612.06370v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 12,
        "abstract": "This paper presents a novel yet intuitive approach to unsupervised feature\nlearning. Inspired by the human visual system, we explore whether low-level\nmotion-based grouping cues can be used to learn an effective visual\nrepresentation. Specifically, we use unsupervised motion-based segmentation on\nvideos to obtain segments, which we use as 'pseudo ground truth' to train a\nconvolutional network to segment objects from a single frame. Given the\nextensive evidence that motion plays a key role in the development of the human\nvisual system, we hope that this straightforward approach to unsupervised\nlearning will be more effective than cleverly designed 'pretext' tasks studied\nin the literature. Indeed, our extensive experiments show that this is the\ncase. When used for transfer learning on object detection, our representation\nsignificantly outperforms previous unsupervised approaches across multiple\nsettings, especially when training data for the target task is scarce.",
        "tag": "[{'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Learning Features by Watching Objects Move",
        "year": 2016,
        "journal": "Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition"
    },
    {
        "author": "Muhammad Ghifary, W. Bastiaan Kleijn, Mengjie Zhang",
        "day": 21,
        "id": "1409.6041v1",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1409.6041v1', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1409.6041v1', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 9,
        "abstract": "We propose a simple neural network model to deal with the domain adaptation\nproblem in object recognition. Our model incorporates the Maximum Mean\nDiscrepancy (MMD) measure as a regularization in the supervised learning to\nreduce the distribution mismatch between the source and target domains in the\nlatent space. From experiments, we demonstrate that the MMD regularization is\nan effective tool to provide good domain adaptation models on both SURF\nfeatures and raw image pixels of a particular image data set. We also show that\nour proposed model, preceded by the denoising auto-encoder pretraining,\nachieves better performance than recent benchmark models on the same data sets.\nThis work represents the first study of MMD measure in the context of neural\nnetworks.",
        "tag": "[{'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Domain Adaptive Neural Networks for Object Recognition",
        "year": 2014,
        "journal": "Pacific Rim international conference on artificial intelligence"
    },
    {
        "author": "Lionel Pigou, Ron van den Oord, 'Sander Dieleman, Mieke Van Herreweghe, Joni Dambre",
        "day": 5,
        "id": "1506.01911v3",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1506.01911v3', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1506.01911v3', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 6,
        "abstract": "Recent studies have demonstrated the power of recurrent neural networks for\nmachine translation, image captioning and speech recognition. For the task of\ncapturing temporal structure in video, however, there still remain numerous\nopen research questions. Current research suggests using a simple temporal\nfeature pooling strategy to take into account the temporal aspect of video. We\ndemonstrate that this method is not sufficient for gesture recognition, where\ntemporal information is more discriminative compared to general video\nclassification tasks. We explore deep architectures for gesture recognition in\nvideo and propose a new end-to-end trainable neural network architecture\nincorporating temporal convolutions and bidirectional recurrence. Our main\ncontributions are twofold; first, we show that recurrence is crucial for this\ntask; second, we show that adding temporal convolutions leads to significant\nimprovements. We evaluate the different approaches on the Montalbano gesture\nrecognition dataset, where we achieve state-of-the-art results.",
        "tag": "[{'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Beyond Temporal Pooling: Recurrence and Temporal Convolutions for\n  Gesture Recognition in Video",
        "year": 2015,
        "journal": "International Journal of Computer Vision"
    },
    {
        "author": "Rakesh Achanta, Trevor Hastie",
        "day": 20,
        "id": "1509.05962v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1509.05962v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1509.05962v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 9,
        "abstract": "In this paper, we address the task of Optical Character Recognition(OCR) for\nthe Telugu script. We present an end-to-end framework that segments the text\nimage, classifies the characters and extracts lines using a language model. The\nsegmentation is based on mathematical morphology. The classification module,\nwhich is the most challenging task of the three, is a deep convolutional neural\nnetwork. The language is modelled as a third degree markov chain at the glyph\nlevel. Telugu script is a complex alphasyllabary and the language is\nagglutinative, making the problem hard. In this paper we apply the latest\nadvances in neural networks to achieve state-of-the-art error rates. We also\nreview convolutional neural networks in great detail and expound the\nstatistical justification behind the many tricks needed to make Deep Learning\nwork.",
        "tag": "[{'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Telugu OCR Framework using Deep Learning",
        "year": 2015,
        "journal": "arXiv preprint arXiv:1509.05962"
    },
    {
        "author": "Jeff Donahue, Trevor Darrell",
        "day": 31,
        "id": "1605.09782v7",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1605.09782v7', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1605.09782v7', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 5,
        "abstract": "The ability of the Generative Adversarial Networks (GANs) framework to learn\ngenerative models mapping from simple latent distributions to arbitrarily\ncomplex data distributions has been demonstrated empirically, with compelling\nresults showing that the latent space of such generators captures semantic\nvariation in the data distribution. Intuitively, models trained to predict\nthese semantic latent representations given data may serve as useful feature\nrepresentations for auxiliary problems where semantics are relevant. However,\nin their existing form, GANs have no means of learning the inverse mapping --\nprojecting data back into the latent space. We propose Bidirectional Generative\nAdversarial Networks (BiGANs) as a means of learning this inverse mapping, and\ndemonstrate that the resulting learned feature representation is useful for\nauxiliary supervised discrimination tasks, competitive with contemporary\napproaches to unsupervised and self-supervised feature learning.",
        "tag": "[{'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Adversarial Feature Learning",
        "year": 2016,
        "journal": "Proceedings of the 26th ACM international conference on Multimedia"
    },
    {
        "author": "Zachary C. Lipton",
        "day": 10,
        "id": "1606.03490v3",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1606.03490v3', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1606.03490v3', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 6,
        "abstract": "Supervised machine learning models boast remarkable predictive capabilities.\nBut can you trust your model? Will it work in deployment? What else can it tell\nyou about the world? We want models to be not only good, but interpretable. And\nyet the task of interpretation appears underspecified. Papers provide diverse\nand sometimes non-overlapping motivations for interpretability, and offer\nmyriad notions of what attributes render models interpretable. Despite this\nambiguity, many papers proclaim interpretability axiomatically, absent further\nexplanation. In this paper, we seek to refine the discourse on\ninterpretability. First, we examine the motivations underlying interest in\ninterpretability, finding them to be diverse and occasionally discordant. Then,\nwe address model properties and techniques thought to confer interpretability,\nidentifying transparency to humans and post-hoc explanations as competing\nnotions. Throughout, we discuss the feasibility and desirability of different\nnotions, and question the oft-made assertions that linear models are\ninterpretable and that deep neural networks are not.",
        "tag": "[{'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "The Mythos of Model Interpretability",
        "year": 2016,
        "journal": "Queue 16.3"
    },
    {
        "author": "Sahil Garg, Irina Rish, Guillermo Cecchi, Aurelie Lozano",
        "day": 22,
        "id": "1701.06106v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1701.06106v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1701.06106v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 1,
        "abstract": "In this paper, we focus on online representation learning in non-stationary\nenvironments which may require continuous adaptation of model architecture. We\npropose a novel online dictionary-learning (sparse-coding) framework which\nincorporates the addition and deletion of hidden units (dictionary elements),\nand is inspired by the adult neurogenesis phenomenon in the dentate gyrus of\nthe hippocampus, known to be associated with improved cognitive function and\nadaptation to new environments. In the online learning setting, where new input\ninstances arrive sequentially in batches, the neuronal-birth is implemented by\nadding new units with random initial weights (random dictionary elements); the\nnumber of new units is determined by the current performance (representation\nerror) of the dictionary, higher error causing an increase in the birth rate.\nNeuronal-death is implemented by imposing l1/l2-regularization (group sparsity)\non the dictionary within the block-coordinate descent optimization at each\niteration of our online alternating minimization scheme, which iterates between\nthe code and dictionary updates. Finally, hidden unit connectivity adaptation\nis facilitated by introducing sparsity in dictionary elements. Our empirical\nevaluation on several real-life datasets (images and language) as well as on\nsynthetic data demonstrates that the proposed approach can considerably\noutperform the state-of-art fixed-size (nonadaptive) online sparse coding of\nMairal et al. (2009) in the presence of nonstationary data. Moreover, we\nidentify certain properties of the data (e.g., sparse inputs with nearly\nnon-overlapping supports) and of the model (e.g., dictionary sparsity)\nassociated with such improvements.",
        "tag": "[{'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Neurogenesis-Inspired Dictionary Learning: Online Model Adaption in a\n  Changing World",
        "year": 2017,
        "journal": "arXiv preprint arXiv:1701.06106 "
    },
    {
        "author": "Weifeng Ge, Yizhou Yu",
        "day": 28,
        "id": "1702.08690v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1702.08690v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1702.08690v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 2,
        "abstract": "Deep neural networks require a large amount of labeled training data during\nsupervised learning. However, collecting and labeling so much data might be\ninfeasible in many cases. In this paper, we introduce a source-target selective\njoint fine-tuning scheme for improving the performance of deep learning tasks\nwith insufficient training data. In this scheme, a target learning task with\ninsufficient training data is carried out simultaneously with another source\nlearning task with abundant training data. However, the source learning task\ndoes not use all existing training data. Our core idea is to identify and use a\nsubset of training images from the original source learning task whose\nlow-level characteristics are similar to those from the target learning task,\nand jointly fine-tune shared convolutional layers for both tasks. Specifically,\nwe compute descriptors from linear or nonlinear filter bank responses on\ntraining images from both tasks, and use such descriptors to search for a\ndesired subset of training samples for the source learning task.\n  Experiments demonstrate that our selective joint fine-tuning scheme achieves\nstate-of-the-art performance on multiple visual classification tasks with\ninsufficient training data for deep learning. Such tasks include Caltech 256,\nMIT Indoor 67, Oxford Flowers 102 and Stanford Dogs 120. In comparison to\nfine-tuning without a source domain, the proposed method can improve the\nclassification accuracy by 2% - 10% using a single model.",
        "tag": "[{'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Borrowing Treasures from the Wealthy: Deep Transfer Learning through\n  Selective Joint Fine-tuning",
        "year": 2017,
        "journal": "Proceedings of the IEEE conference on computer vision and pattern recognition"
    },
    {
        "author": "Tanmay Gupta, Kevin Shih, Saurabh Singh, Derek Hoiem",
        "day": 2,
        "id": "1704.00260v2",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1704.00260v2', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1704.00260v2', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 4,
        "abstract": "An important goal of computer vision is to build systems that learn visual\nrepresentations over time that can be applied to many tasks. In this paper, we\ninvestigate a vision-language embedding as a core representation and show that\nit leads to better cross-task transfer than standard multi-task learning. In\nparticular, the task of visual recognition is aligned to the task of visual\nquestion answering by forcing each to use the same word-region embeddings. We\nshow this leads to greater inductive transfer from recognition to VQA than\nstandard multitask learning. Visual recognition also improves, especially for\ncategories that have relatively few recognition training labels but appear\noften in the VQA setting. Thus, our paper takes a small step towards creating\nmore general vision systems by showing the benefit of interpretable, flexible,\nand trainable core representations.",
        "tag": "[{'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Aligned Image-Word Representations Improve Inductive Transfer Across\n  Vision-Language Tasks",
        "year": 2017,
        "journal": "Proceedings of the IEEE International Conference on Computer Vision"
    },
    {
        "author": "Jan Hendrik Metzen, Mummadi Chaithanya Kumar, Thomas Brox, Volker Fischer",
        "day": 19,
        "id": "1704.05712v3",
        "link": "[{'rel': 'alternate', 'href': 'http://arxiv.org/abs/1704.05712v3', 'type': 'text/html'}, {'rel': 'related', 'href': 'http://arxiv.org/pdf/1704.05712v3', 'type': 'application/pdf', 'title': 'pdf'}]",
        "month": 4,
        "abstract": "While deep learning is remarkably successful on perceptual tasks, it was also\nshown to be vulnerable to adversarial perturbations of the input. These\nperturbations denote noise added to the input that was generated specifically\nto fool the system while being quasi-imperceptible for humans. More severely,\nthere even exist universal perturbations that are input-agnostic but fool the\nnetwork on the majority of inputs. While recent work has focused on image\nclassification, this work proposes attacks against semantic image segmentation:\nwe present an approach for generating (universal) adversarial perturbations\nthat make the network yield a desired target segmentation as output. We show\nempirically that there exist barely perceptible universal noise patterns which\nresult in nearly the same predicted segmentation for arbitrary inputs.\nFurthermore, we also show the existence of universal noise which removes a\ntarget class (e.g., all pedestrians) from the segmentation while leaving the\nsegmentation mostly unchanged otherwise.",
        "tag": "[{'term': 'stat.ML', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.AI', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.CV', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.LG', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}, {'term': 'cs.NE', 'scheme': 'http://arxiv.org/schemas/atom', 'label': None}]",
        "name": "Universal Adversarial Perturbations Against Semantic Image Segmentation",
        "year": 2017,
        "journal": "Proceedings of the IEEE International Conference on Computer Vision"
    }
    
 ]