/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:36b4f7c3-8b0d-462a-beb4-4fe0a56fdeab",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_i4s9l5xY0",
    "aws_user_pools_web_client_id": "40h38bolungebkhh4vkbrtn0d2",
    "oauth": {
        "domain": "amrsocialnetwork-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8080/",
        "redirectSignOut": "http://localhost:8080/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://ymk7xtlha5ex7ljyumc7dxlkfq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
