/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:0ecf4e5e-2886-4265-9fb5-217c4f91fba6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_8jDOP09Ey",
    "aws_user_pools_web_client_id": "4jh4cf23se277fbct2ib7o34ne",
    "oauth": {
        "domain": "amrsocialnetwork-facebook-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8080/",
        "redirectSignOut": "http://localhost:8080/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://c5brcgpuvfegnbgo5zb4szlmqa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
